### ISSUE TITLE
Laggy if you have 20k+ cards

### ISSUE THREAD

**Issue by Kaorukaoru12345** [Kuuuube/kanjigrid#1]
It's great but it takes up to 1 minute to open the selection menu and another one to show all the kanji
Other decks that have less cards are quick though

On my office pc that doesn't have a SSD it's even worse

**Comment by Kuuuube** [comment]
I test kanji grid on 100k+ card collections. I'm unable to replicate the selection menu opening slow but the slow generation of the grid is unfortunately expected.

For the selection menu, the only selection menu call that could possibly cause lag is fetching the note models. But this is handled purely in anki's api and outside of my control.

For the grid generation, this can be blamed on python being slow at loops and large strings. It would be great if anki supported another language to write addons in but at the moment we're stuck with python.

As much as I would like to further improve the addon, it really isn't feasible. If you or anyone else finds some crucial optimization I've overlooked, please let me know.
