### ISSUE TITLE
[Bug] Memory leak

### ISSUE THREAD

**Issue by iamllama** [Kuuuube/kanjigrid#10]
Before opening and closing kanjigrid thrice:
![image](https://github.com/user-attachments/assets/aaf6f543-0df9-4f1c-a7de-bf14497e2cee)
After:
![image](https://github.com/user-attachments/assets/c4f5b8b1-fd1c-4a57-b1ee-b2e2da9fd447)

Same behaviour on wsl.

Opening and closing the deck stats window, in comparison, doesn't leave the webview process behind.

Not really much of an issue, but it does add up. And it defeats the purpose of having a gc and having to put up with python xD

**Comment by Kuuuube** [comment]
Gave this some testing and I can't find any way to fix this. I'm probably just looking for the wrong thing but between Qt having some of the most horrendous documentation and Anki's version of Qt slightly differing in some areas I have no clue what's wrong.

I've tried setting the `WA_DeleteOnClose` attribute, hooking `closeEvent` and calling `deleteLater` and `destroy` on both the window and webview, and setting parent/child to try to make it automatically clean up.

Feel free to make a PR if you figure this out or comment with more information here.

**Comment by Kuuuube** [comment]
Nvm, got it. Anki has webviews set up to have a built in cleanup method and apparently using any other way to clean them up doesnt work.

**Comment by iamllama** [comment]
> Nvm, got it. Anki has webviews set up to have a built in cleanup method and apparently using any other way to clean them up doesnt work.

Tried a bunch of approaches (setting references to none, threading `win` and `wv` thru calls instead of having `self` owning them, and calling `mw.garbage_collect_on_dialog_finish` but none of them worked. Can't believe I forgot to check for a cleanup fun in the webview class itself xD.

Thanks for the prompt resolution Kuuube! 🎉
