### ISSUE TITLE
[Feature request] "Time travel" to see grid as it would've been in the past

### ISSUE THREAD

**Issue by iamllama** [Kuuuube/kanjigrid#17]
It'd be nice to have a time travel feature to show what the grid looked liked at a certain date/time. For looking back at the progress one's made or etc.

Then again maybe spending too much time in the past could be detrimental, which might be why it wasn't already added 😅

**Comment by iamllama** [comment]
I've done a bit of work on this, and have come up with two solutions so far:

1) Query the db for each card's latest revlog interval that falls within the timeframe
```py
def handleTimeTravel(card, timetravel):
    # get ivl from the latest review (if any) during the timetravel timeframe
    _max_id, ivl = mw.col.db.first(f"select max(id), ivl from revlog where cid = {card.id} and id <= {timetravel}")
    if ivl is None:
        # card was not reviewd during the timeframe...
        if card.id <= timetravel:
            # ...but was still present in deck,
            # so patch it to be of type "new" (to emulate existing behaviour)
            card.ivl = 0
            card.type = 0
        else:
            # ...and wasn't in deck either, so it shouldn't be counted
            return False
    else:
        # https://github.com/open-spaced-repetition/fsrs4anki/issues/326#issuecomment-1613441410
        # a -ve ivl is in seconds, +ve ivl is in days
        # -(ivl // (60 * 60 * 24)) would round up instead
        card.ivl = ivl if ivl >= 0 else (-ivl) // (60 * 60 * 24)

    return True

def addUnitData2(units, unitKey, i, card, kanjionly, timetravel, revlog):
    validKey = data.ignore.find(unitKey) == -1 and (not kanjionly or isKanji(unitKey))
    if not validKey:
        return

    # handleTimeTravel mutates card and returns a bool indicating if it should count towards the grid
    if timetravel is not None and not handleTimeTravel(card, timetravel):
        return
  
    if unitKey not in units:
        unit = unit_tuple(0, unitKey, 0.0, 0)
        units[unitKey] = unit

    units[unitKey] = addDataFromCard(units[unitKey], i, card)
```

2) Gather the revlog data along with `cids`
```py
deck_ids = ids2str(dids)
        config.revlog = {}
        if not config.tt2 and config.timetravel is not None:
            revlog_rows = mw.col.db.all(f"""select cid, max(id), ivl
from revlog 
where 
cid in (select id from cards where did in {deck_ids} or odid in {deck_ids}) 
and 
id <= {config.timetravel}
group by cid
order by cid asc
""")
            config.revlog = {row[0]: row[2] for row in revlog_rows} # cid -> ivl
```
and then
```py
def addUnitData(units, unitKey, i, card, kanjionly, timetravel, revlog):
    validKey = data.ignore.find(unitKey) == -1 and (not kanjionly or isKanji(unitKey))
    if validKey:
        if card.id not in revlog:
            if card.id > timetravel:
                 return
            card.ivl = 0
            card.type = 0
        else:
            revlog_ivl = revlog[card.id]
            card.ivl = revlog_ivl if revlog_ivl >= 0 else (-revlog_ivl) // (60 * 60 * 24)
        if unitKey not in units:
            unit = unit_tuple(0, unitKey, 0.0, 0)
            units[unitKey] = unit
        units[unitKey] = addDataFromCard(units[unitKey], i, card)
```
(pretty much identical to the 1st solution's addUnitData, difference being the `revlog` dict used instead of querying the db

The drawback of the 1st soln. is that having an extra db query per card is slow. On my collection/system it adds 300ms to the baseline. The 2nd soln by comparison adds ~10ms.

The drawback of the 2nd soln is that it doesn't work when `mw.col.find_cards` is used :/

There are also discrepancies with the resulting grid and what the actual past grid looked like:
- Revlog intervals and card intervals don't always match up, especially if the card is relearnt.
- The card could've been edited anytime, and only its latest contents will be used in the grid.

**Comment by iamllama** [comment]
> Revlog intervals and card intervals don't always match up

Here's an example:
This card has an interval of 7
![image](https://github.com/user-attachments/assets/12e69369-8f50-4779-ba88-36da26f82c43)
But its latest corresponding review has an interval of -43200 (negative means seconds)
![image](https://github.com/user-attachments/assets/4963e03f-ed41-4f06-8ae1-3a46f9091c04)

lastIvl isn't consistent either, there are cards with revlog entries where both ivl and lastIvl are in seconds and don't correspond to the card's interval

**Comment by Kuuuube** [comment]
This sounds like a headache waiting to happen. I'm not totally against the feature but the filtering/processing needs to be very clean or isolated (for example a filter that is run over the card data before processing) to not tangle up with the existing code for that.

**Comment by iamllama** [comment]
> but the filtering/processing needs to be very clean or isolated (for example a filter that is run over the card data before processing)

The added code in `addUnitData` can be moved over to 
https://github.com/Kuuuube/kanjigrid/blob/ef31eda8527510b1c52b1d283226dd248632b459/generate_grid.py#L155-L156
to change it into
```py
for i in cids:
    card = mw.col.get_card(i)
    if not handleTimeTravel(card, config):
        continue # card shouldn't be counted
    ...
```
for example

> Also you can probably get a decent view of the past already just by adding some sort of date range to the additional search filters. Obviously the strength colors wont be accurate but the kanji should be.

That's true, someone could play around with `rated` and `added` to get an approximation

**Comment by iamllama** [comment]
On seeing this nugget from fsrs helper, I wonder if it might not be unfeasible to just shove the `cids` from either `mw.col.find_cards` and `mw.col.db.list` into the query instead of select-ing xD
```py
    revlog_ids = mw.col.db.list(
        """
        SELECT cur.id
        FROM revlog as cur
        WHERE cur.type >= 4
        AND cur.factor <> 0
        AND (
        SELECT type
        FROM revlog
        WHERE id = (
                SELECT min(id)
                FROM revlog
                WHERE id > cur.id
                AND cid == cur.cid
            )
        ) >= 4
    """
    )
    cnt = len(revlog_ids)
    mw.col.db.execute(f"DELETE FROM revlog WHERE id IN {ids2str(revlog_ids)}")
```
