### ISSUE TITLE
Feature Request for grouping Traditiional Characters by ranking as per Humanum

### ISSUE THREAD

**Issue by Kirchheim** [Kuuuube/kanjigrid#18]
Group characters by frequency rank from this site
https://humanum.arts.cuhk.edu.hk/Lexis/lexi-can/
I cannot get direct link, but if you click menu left "Ranking Chart", you see the table I refer to

I have downloaded that table manually and converted it to attached csv file
[Humanum-Hanzi-Rank-comma-delimited.csv](https://github.com/user-attachments/files/17742394/Humanum-Hanzi-Rank-comma-delimited.csv)

**Comment by Kirchheim** [comment]
Group per 1000 sound good to me

Am 14.11.2024 um 04:41 schrieb Kuuuube ***@***.***>:


How are you thinking this should be grouped? Maybe one group for each 1000 characters? For example, kanji grid includes a grouping for the JPDB kanji frequency list which uses this way to group. https://github.com/Kuuuube/kanjigrid/blob/master/data/jpdb_kanji_frequency_list.json

**Comment by Kuuuube** [comment]
Added! I set the language for this to `zh-Hant` (traditional characters), please let me know if that is incorrect.

**Comment by Kirchheim** [comment]
The Cantonese ranking Words.hk <http://words.hk/> and Humanum are all based on Hong Kong, 
and Hong Kong uses Traditional Characters only

https://www.wikidata.org/wiki/Q18130932

so zh-Hant is correct.


Thanks.

Am 14.11.2024 um 05:39 schrieb Kuuuube ***@***.***>:


Added! I set the language for this to zh-Hant (traditional characters), please let me know if that is incorrect.
