### ISSUE TITLE
Feature Request for grouping Traditiional Characters by ranking as Words.hk

### ISSUE THREAD

**Issue by Kirchheim** [Kuuuube/kanjigrid#19]
Words.hk has published a dictionary of colloquial Cantonese and also frequency files for colloquial Cantonese
The Humanum character ranking is based on a written corpus of Cantonese, which has frequency rankings quite different from spoken Cantonese; here we  now have a ranking of spoken Cantonese characters

The data is here
https://words.hk/faiman/analysis/
specifically "character usage frequency", since this add-on is about characters
I have cleaned up the Words.hk list to keep only Chinese Characters, attached see [Cantocharrank.csv]
[Cantocharrank.csv](https://github.com/user-attachments/files/17742455/Cantocharrank.csv)

**Comment by Kuuuube** [comment]
Added! Thank you for your suggestions and providing this data. There should be a new release out either tonight or tomorrow with the new groupings.

**Comment by Kirchheim** [comment]
No, all the kudos is on you, and this menu to choose - that’s really geat !!
Much appreciated.

Am 14.11.2024 um 05:49 schrieb Kuuuube ***@***.***>:


Added! Thank you for your suggestions and providing this data. There should be a new release out either tonight or tomorrow with the new groupings.
