### ISSUE TITLE
[Feature request] Add support for JIS levels

### ISSUE THREAD

**Issue by epistularum** [Kuuuube/kanjigrid#2]
JIS levels are a set of 4 levels from 1 to 4 based on character frequency as described by the JIS X 0213 standard.

Feel free to use the data I compiled here:
https://github.com/epistularum/kanji-restoration/blob/f8ebdeda503efe2712f2ffd05cc6cc088f0d73ca/source/standards/%EF%BC%88%E6%97%A5%E6%9C%AC%E7%94%A3%E6%A5%AD%E8%A6%8F%E6%A0%BC%EF%BC%89JIS%20X%200213.tsv

**Comment by Kuuuube** [comment]
Added. I'll have a new release out soon.
