### ISSUE TITLE
Feature Request for grouping characters by the 1000 character list

### ISSUE THREAD

**Issue by Kirchheim** [Kuuuube/kanjigrid#20]
There is a list of 1000 characters that stems from the "Thousand Character Classic", see Wikpedia link for history, 
essentially what Chinese kids had to learn at the time by heart.

 https://en.wikipedia.org/wiki/Thousand_Character_Classic 

I have compiled attached csv file for easy loading
[OneThousandCharacters.csv](https://github.com/user-attachments/files/17742483/OneThousandCharacters.csv)

**Comment by Kuuuube** [comment]
Are you sure that data is correct? Looking at the data provided by wikipedia, it doesnt match (https://en.wikipedia.org/wiki/Thousand_Character_Classic#Text). And it also isnt 1000 characters whereas the one on wikipedia is.

The wikipedia data stripped of formatting: [characters.csv](https://github.com/user-attachments/files/17742591/characters.csv)

**Comment by Kirchheim** [comment]
no, not sure, I compiled that list myself, and I am not a good programmer

actually, I used ChatGPT to create the file, and then used ChatGPT to create a Python program,
and then loaded the whole stuff with AnkiConnect into a field in my Anki deck for characters for motivation

I had just hoped it would be more or less correct, that’s why I am glad your Add-on come up

Am 14.11.2024 um 04:55 schrieb Kuuuube ***@***.***>:


Are you sure that data is correct? Looking at the data provided by wikipedia, it doesnt match (https://en.wikipedia.org/wiki/Thousand_Character_Classic#Text). And it also isnt 1000 characters whereas the one on wikipedia is.

The wikipedia data stripped of formatting: characters.csv <https://github.com/user-attachments/files/17742591/characters.csv>

**Comment by Kuuuube** [comment]
Alright, I compiled what seems to be correct comparing from a few sources. There are some encoding disagreements between sources so I'm not sure this can be perfect. I added what I can best tell to be correct, it will be released in the next update.

**Comment by Kirchheim** [comment]
Thank you !!

Am 14.11.2024 um 05:15 schrieb Kuuuube ***@***.***>:


Alright, I compiled what seems to be correct comparing from a few sources. There are some encoding disagreements between sources so I'm not sure this can be perfect. I added what I can best tell to be correct, it will be released in the next update.
