### ISSUE TITLE
[Feature Request] Allow default "Sort by" option in config

### ISSUE THREAD

**Issue by PANICBUTT0N** [Kuuuube/kanjigrid#21]
The default "Sort-by" option, which used to just be none, is now "Score". With no option to set it to none by default, it is rather inconvenient to have to set it in the GUI every time the add-on is used. An option in the config similar to the "Group by" index based option would be helpful.

**Comment by Kuuuube** [comment]
Set the `sortby` config value to 0. If you do not see it, you can either add the key manually or reset to defaults.

**Comment by PANICBUTT0N** [comment]
Thank you!
