### ISSUE TITLE
Suspended Cards's Kanji should also be shown as Strong

### ISSUE THREAD

**Issue by MuhammadShahzeb123** [Kuuuube/kanjigrid#24]
For the most part I love this tool because it actually allow me to see all the countries that I have remembered so far, but there is one little problem. We should also be getting the Kanji's from the cards that are suspended as shown as Strong (Full) cause I know them so well that I can't forget that's why they are suspended. 

ありがとう

**Comment by Kuuuube** [comment]
This directly conflicts with people who use the "suspend leeches" anki setting. Those suspended cards would be their least well known.

Are you suspending cards before you've reviewed them? After they have been pushed out to >=180 day interval (by default) they will be shown as strong anyways.

**Comment by Kuuuube** [comment]
The only cards that should be filtered out are ones that are new (have no reviews).

If you have one suspended card with a very high interval but another card with a lower interval, if both contain one of the same kanji, an average is taken. You can see which cards are counted for each kanji by right clicking and selecting `Browse deck for x` (although this does show cards with no reviews).

**Comment by MuhammadShahzeb123** [comment]
Okay okay... Now I get it. 

I was totally missing on this interval calculation part that shows how strong you remember a Kanji. ごめんなさい

Seems like I have to create my own code to get all the Kanji I know so far. 

Sorry again for causing troble. 

I have managed to remember the meaning (and 95% of the Kanji's Readings) of almost 900 Kanji in only 6 months so I was a bit excited to find out...

**Comment by Kuuuube** [comment]
All good. If you're writing your own tool maybe the txt or json export of kanjigrid could be helpful.

Going to close this now.
