### ISSUE TITLE
[Feature request] Finding kanji within the grid

### ISSUE THREAD

**Issue by iamllama** [Kuuuube/kanjigrid#25]
The timetravel feature made me stop exporting to html daily like a madman xD, but it made also me realise that i was using it as a crutch to ctrl-f for kanji in the browser.

It'd be very handy to search for a kanji within a grid, to see what category it'd fit into based on the grouping (grade/jlpt/tmw/etc.)

**Comment by Kuuuube** [comment]
If theres some way to enable this on the webview window then this could probably work. But I'm not sure about adding this to the html page itself.
