### ISSUE TITLE
Version 1.4.3 failed to load

### ISSUE THREAD

**Issue by Rinkerbel** [Kuuuube/kanjigrid#3]
This is the debug info I got from Anki

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Kanji Grid Kuuube:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\Rick\scoop\persist\anki\data\addons21\1610304449\__init__.py", line 22, in <module>
    from . import config_util, data, util, save
  File "C:\Users\Rick\scoop\persist\anki\data\addons21\1610304449\util.py", line 64
    match i:
          ^
SyntaxError: invalid syntax

**Comment by Kuuuube** [comment]
You need to update python. 3.10 or higher is required for match statements. 3.10 was released 3 years ago so I think it's reasonable to expect users to have at least that version.

3.9 isn't out of support until next year but unless theres some major reason you cannot update python, I don't plan on reverting from using a match statements.

**Comment by Kuuuube** [comment]
Scratch that. This is a packaging issue with Anki itself. They are shipping extremely out of date python versions with windows releases and it doesn't seem like this has an easy resolution on windows.

I run linux so didn't catch this issue in testing. Sorry about that I'll get a release out to fix this soon.

**Comment by Kuuuube** [comment]
I've pushed a new release, check for updates in Anki and it should be back to working. Thank you for the quick report on this issue.

**Comment by Eodis** [comment]
Not sure if this is related to my issue but i can't use the addon since i updated Anki to 24.10 Beta (windows). When trying to generate a grid it just crashes Anki and your last update doesn't seem to fix that.

I tried every "Video driver" option as i saw there was a "Known Issues" about that even though it's for linux users but it's still crashing.

**Comment by Kuuuube** [comment]
> Not sure if this is related to my issue

It is certainly unrelated. I've mentioned this bug and given steps to reproduce in the 24.10 beta thread. https://forums.ankiweb.net/t/anki-24-10-beta/49989/109?u=kuuube

This is not something I can fix on my end.

**Comment by Kuuuube** [comment]
The issue from 2.10 beta has been fixed https://github.com/ankitects/anki/commit/6aff3c5f8056a24f796c47e9f5277c76fda2a73c.

Update to [24.10 Beta 2](https://github.com/ankitects/anki/releases/tag/24.10beta2). @Eodis
