### ISSUE TITLE
Incorrect missing/found numbers and percentage for the duolingo grouping

### ISSUE THREAD

**Issue by iamllama** [Kuuuube/kanjigrid#31]
The reported numbers (missing/found) don't seem to line up with the grid when using the duolingo grouping

To clarify, this doesn't look like 46.86%

![image](https://github.com/user-attachments/assets/0071bdae-3db7-4fca-a001-86d59cae282e)

Contrast with a group from the jlpt set, for example:
![image](https://github.com/user-attachments/assets/45131e8d-7382-4cff-9577-6c6c77520aed)

EDIT: Ah i think they overlap. The grid doesn't seem to like that

**Comment by Kuuuube** [comment]
Fixed in 9dedb91e248a15e41e63395eca828b88a337eeee
