### ISSUE TITLE
Add groupings for Chinese Traditional Characters as per Standard Form of National Characters (Taiwan)

### ISSUE THREAD

**Issue by Kirchheim** [Kuuuube/kanjigrid#32]
The Taiwan standardization is explained here: https://en.wikipedia.org/wiki/Standard_Form_of_National_Characters

The first list of characters comprises Chart of Standard Forms of Common National Characters (Chinese: 常用國字標準字體表), including 4,808 commonly used Chinese characters.
The 4,804 list is here: https://language.moe.gov.tw/001/Upload/Files/site_content/download/mandr/教育部4808個常用字.pdf

The second list of characters comprises Chart of Standard Forms of Less-Than-Common National Characters (Chinese: 次常用國字標準字體表), including secondary commonly used 6,329 characters.
The list is here: https://zh.wikisource.org/wiki/次常用國字標準字體表?utm_source=chatgpt.com
It says 6343, probably some variants.

The third list, above and beyond, we can forget - also no direct link available.

**Comment by Kuuuube** [comment]
I think there are certainly people who would like to see that third list. Some kanjigrid users enjoy finding the very rare characters. But if it's too hard to get that list it's okay.

I'll take a look at getting these two lists added.

**Comment by Kuuuube** [comment]
Added in 30b96e394fb3676b457f410fee2573264a9ef3d9.

**Comment by Kirchheim** [comment]
I will keep searching for the third list - it’s just not available with the link and sources I forwarded.
Did I say your concept of „grouping“ is pretty cool and versatile?

Am 30.12.2024 um 16:04 schrieb Kuuuube ***@***.***>:


I think there are certainly people who would like to see that third list. Some kanjigrid users enjoy finding the very rare characters. But if it's too hard to get that list it's okay.

I'll take a look at getting these two lists added.

**Comment by Kirchheim** [comment]
I found this source for the third list "Chart of Rarely-Used National Characters (Chart C)"
https://github.com/TraditionalChinese/TW-ABCN

In the About, it says

About

On the internet, only textual versions of Taiwan's Chart of Standard Forms of Common National Characters and Chart of Standard Forms of Less-Than-Common National Characters (i.e., Chart A and Chart B) are available. The Chart of Rarely-Used National Characters (Chart C) is not provided. This version has been compiled into a textual format based on the standard character charts included in the appendix of the Dictionary of Variant Chinese Characters for reference purposes. The sixth official edition of the Dictionary of Variant Chinese Characters states that there are a total of 29,921 characters in these charts. However, after compilation, the total count is 29,923 characters. It is unclear where the discrepancy lies, and it is hoped that readers can identify and correct any errors.

The number is different from the Wiki link, but I guess later versions, more variants, etc.
Even the author of this github list acknowledges there are some discrepencies, albeit small.


There is more info here

https://forum.freemdict.com/t/topic/20907

Based on the sixth edition

On the internet, only textual versions of Taiwan's Chart of Standard Forms of Common National Characters (Chart A) and Chart of Standard Forms of Less-Than-Common National Characters (Chart B) are available. The Chart of Rarely-Used National Characters (Chart C) does not exist in an electronic format. This textual version has been compiled manually based on the standard character charts in the appendix of the Dictionary of Variant Chinese Characters for reference and use.

The appendix of the sixth official edition of the Dictionary of Variant Chinese Characters states a total of 29,921 characters. However, after compilation, the actual count is 29,923 characters. It is unclear which statistical data contains the error, and it is hoped that this can be jointly verified to identify and correct any discrepancies. (This pertains to the sixth edition. The currently available seventh edition includes a total of 29,920 characters.)

Breakdown:
	- Chart of Standard Forms of Common National Characters (commonly referred to as Chart A): 4,808 characters
	- Chart of Standard Forms of Less-Than-Common National Characters (commonly referred to as Chart B): 6,329 characters
	- Chart of Rarely-Used National Characters (commonly referred to as Chart C): 18,319 characters

The total number of characters in Charts A, B, and C, as described in the appendix editing notes of the Dictionary of Variant Chinese Characters, matches the character counts stated. However, the Newly Added Standard Characters (N) are described as 465 characters in the editing notes but are actually calculated as 467 characters based on the dictionary, bringing the total to 29,923 characters. Please note this discrepancy. (These figures are based on the sixth edition.)

In March 2024, the seventh official edition was released. Some adjustments were made to the characters, and three characters from the sixth edition were removed:
	1.	䗤 (Character ID in the sixth edition: C12423)
	2.	㹮 (Character ID in the sixth edition: N00508)
	3.	䘃 (Character ID in the sixth edition: N00513)

Thus, the total number of characters is now 29,920.
(The download links below are for the sixth edition. To use the seventh edition, simply remove the three characters mentioned above. A separate upload of the seventh edition character chart will not be provided.)

Character ID Explanation:

All standard characters are assigned a character ID to indicate their source:
	- "A": Common characters
	- "B": Less-than-common characters
	- "C": Rarely-used characters
	- "N": Newly added standard characters

The numbers following the letters correspond to the character IDs in the original charts.

PDF and Excel versions are provided below for download.

GitHub Download Link: This is for the sixth edition.

https://forum.freemdict.com/uploads/short-url/2soA23qGEWadVlEwxgvaEaTTCQm.xlsx
https://forum.freemdict.com/uploads/short-url/kgYSFX1uMsGMT9JOJDdl5Fzm26H.pdf


And here is the official list (744 pages one has to click through)
https://dict.variants.moe.edu.tw/appendix.jsp?ID=3




Am 30.12.2024 um 16:04 schrieb Kuuuube ***@***.***>:


I think there are certainly people who would like to see that third list. Some kanjigrid users enjoy finding the very rare characters. But if it's too hard to get that list it's okay.

I'll take a look at getting these two lists added.
