### ISSUE TITLE
Original and second source versions of the Third Taiwan MoE List: Chart of Rarely-Used National Characters (Chart C) (6th edition)

### ISSUE THREAD

**Issue by Kirchheim** [Kuuuube/kanjigrid#33]
Grouping of Traditional Chinese Characters by Third list of Rarely-Used National Characters (Chart C)

(A)
I found this source on github for the third list "Chart of Rarely-Used National Characters (Chart C)"
https://github.com/TraditionalChinese/TW-ABCN
It is a derived source, and In the About, it says

About

On the internet, only textual versions of Taiwan's Chart of Standard Forms of Common National Characters and Chart of Standard Forms of Less-Than-Common National Characters (i.e., Chart A and Chart B) are available. The Chart of Rarely-Used National Characters (Chart C) is not provided. This version has been compiled into a textual format based on the standard character charts included in the appendix of the Dictionary of Variant Chinese Characters for reference purposes. The sixth official edition of the Dictionary of Variant Chinese Characters states that there are a total of 29,921 characters in these charts. However, after compilation, the total count is 29,923 characters. It is unclear where the discrepancy lies, and it is hoped that readers can identify and correct any errors.

The number is different from the Wiki link, but I guess later versions, more variants, etc.
Even the author of this github list acknowledges there are some discrepencies, albeit small.

(B)
Then,  There is more info here

https://forum.freemdict.com/t/topic/20907

Based on the sixth edition

On the internet, only textual versions of Taiwan's Chart of Standard Forms of Common National Characters (Chart A) and Chart of Standard Forms of Less-Than-Common National Characters (Chart B) are available. The Chart of Rarely-Used National Characters (Chart C) does not exist in an electronic format. This textual version has been compiled manually based on the standard character charts in the appendix of the Dictionary of Variant Chinese Characters for reference and use.

The appendix of the sixth official edition of the Dictionary of Variant Chinese Characters states a total of 29,921 characters. However, after compilation, the actual count is 29,923 characters. It is unclear which statistical data contains the error, and it is hoped that this can be jointly verified to identify and correct any discrepancies. (This pertains to the sixth edition. The currently available seventh edition includes a total of 29,920 characters.)

Breakdown:
	- Chart of Standard Forms of Common National Characters (commonly referred to as Chart A): 4,808 characters
	- Chart of Standard Forms of Less-Than-Common National Characters (commonly referred to as Chart B): 6,329 characters
	- Chart of Rarely-Used National Characters (commonly referred to as Chart C): 18,319 characters

The total number of characters in Charts A, B, and C, as described in the appendix editing notes of the Dictionary of Variant Chinese Characters, matches the character counts stated. However, the Newly Added Standard Characters (N) are described as 465 characters in the editing notes but are actually calculated as 467 characters based on the dictionary, bringing the total to 29,923 characters. Please note this discrepancy. (These figures are based on the sixth edition.)

In March 2024, the seventh official edition was released. Some adjustments were made to the characters, and three characters from the sixth edition were removed:
	1.	䗤 (Character ID in the sixth edition: C12423)
	2.	㹮 (Character ID in the sixth edition: N00508)
	3.	䘃 (Character ID in the sixth edition: N00513)

Thus, the total number of characters is now 29,920.
(The download links below are for the sixth edition. To use the seventh edition, simply remove the three characters mentioned above. A separate upload of the seventh edition character chart will not be provided.)

Character ID Explanation:

All standard characters are assigned a character ID to indicate their source:
	- "A": Common characters
	- "B": Less-than-common characters
	- "C": Rarely-used characters
	- "N": Newly added standard characters

The numbers following the letters correspond to the character IDs in the original charts.

PDF and Excel versions are provided below for download.

GitHub Download Link: This is for the sixth edition.

https://forum.freemdict.com/uploads/short-url/2soA23qGEWadVlEwxgvaEaTTCQm.xlsx
https://forum.freemdict.com/uploads/short-url/kgYSFX1uMsGMT9JOJDdl5Fzm26H.pdf

(C) Finally, a link to the official MoE source

Official list of 744 pages one has to click through;
https://dict.variants.moe.edu.tw/appendix.jsp?ID=3

Am 30.12.2024 um 16:04 schrieb Kuuuube <notifications@github.com>:

I think there are certainly people who would like to see that third list. Some kanjigrid users enjoy finding the very rare characters. But if it's too hard to get that list it's okay.

I'll take a look at getting these two lists added.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.

**Comment by Kuuuube** [comment]
Thank you! Added in 4cdd7e5ba30e9728654979bd0d3b38c93fc3e6d1. Not going to push a new release for this right away but it will be in the next release.

**Comment by Kuuuube** [comment]
Though I should note that out of the 18319 characters in Chart C, 10 were duplicates. This could be due to unicode not representing every character so variants are used for those 10 or maybe there is a mistake in the list. Kanjigrid lists can't have duplicates in them so I removed those 10 characters.

Not a huge issue but it's worth mentioning. If you see the number is slightly off, that is why.
