### ISSUE TITLE
[Feature request] Clicking on found/known kanji opens deck browser

### ISSUE THREAD

**Issue by iamllama** [Kuuuube/kanjigrid#4]
It would be very handy if clicking on a found/known kanji in the grid opened up the deck browser, instead of redirecting to Jisho (or the url in `jasearch`). This is especially useful for self-made decks where the creator already has an idea of what they mean and want to see what cards reference it.

It could be added as an option in config or the options window, so as to keep and default to the original behaviour (jasearch)

Right now i've cobbled this together to get the same effect:

util.py:
```diff
-def get_search(config, char):
+def get_search(config, char, count):
+    if count: # keep jasearch for missing/unknown kanji
+      return f"javascript:bridgeCommand('deck:current {char}');"
    search_url = ""
    if config.lang == "ja":
        search_url = config.jasearch
    ...
```

\_\_init\_\_.py:
```diff
from anki.utils import ids2str
+import aqt
...

class KanjiGrid:
    def __init__(self, mw):
        if mw:
            self.menuAction = QAction("Generate Kanji Grid", mw, triggered=self.setup)
            mw.form.menuTools.addSeparator()
            mw.form.menuTools.addAction(self.menuAction)
+            self._mw = mw

    def generate(self, config, units):
        ...
-                tile += "<a href=\"" + util.get_search(config, char) + "\" style=\"color:" + color + ";\">" + char + "</a>"
+                tile += "<a href=\"" + util.get_search(config, char, count) + "\" style=\"color:" + color + ";\">" + char + "</a>"
        ...

+    def browse(self, search: str) -> None:
+        browser = aqt.dialogs.open("Browser", self._mw)
+        browser.form.searchEdit.lineEdit().setText(search)
+        browser.onSearchActivated()

    def displaygrid(self, config, deckname, units):
        self.generate(config, units)
        self.timepoint("HTML generated")
        self.win = QDialog(mw)
        self.wv = AnkiWebView()
+        self.wv.set_bridge_command(self.browse, None)
        ...
```

Thanks for your time!

**Comment by iamllama** [comment]
Right I forgot the chosen deck can be changed in the options window, and chose "deck:current" as a quick fix. One way might be to change `get_search`'s signature to accept `deckname` and then include it in the call to `bridgeCommand`

```diff
-def get_search(config, char, count):
+def get_search(config, char, count, deckname):
    if count:
-      return f"javascript:bridgeCommand('deck:current {char}');"
+      return f"javascript:bridgeCommand('&quot;deck:{deckname}&quot; {char}');"
```

It'd be interesting to include the "additional search filters" as well, but that'd take some refactoring to be able to pass the exp at https://github.com/Kuuuube/kanjigrid/blob/74c59a339850d2526883d999ee0e56607bbd016f/__init__.py#L185 to `get_search`

Also, as it stands, this impl breaks saving to HTML, since `bridgeCommand` doesn't exist outside of anki. But it would be easy enough to add a shim to check for that and redefine it to open the dictionary link

**Comment by Kuuuube** [comment]
Ah! Thanks for pointing that out. I didn't realize you had hardcoded a deck in the bridge command.

I've added this. I'll push a new release soon.
